### ISSUE TITLE
Doesn't work with --work-tree option to git checkout command

### ISSUE THREAD

**Issue by johnbendi** [jlehmann/git-submod-enhancements#2]
```
A
├── B
├── C
│   ├── D
│   │   └── .git
│   └── E
│       └── .git
└── .git

```

git doesn't checkout D and E with `--recursive-submodules` option.

**Comment by hvoigt** [comment]
We do not use the bug tracker here. Please write an email with your complete report (the exact commands to reproduce and what you expected) to: git@vger.kernel.org
See https://git-scm.com/community. This is only a repository to track submodule development.
